### PR TITLE
Add Cinnamon Version explicitly to avoid installing it as makedepends

### PR DESCRIPTION
**Pull request by jhbruhn**
This fixes a problem installing this package on systems which don't have cinnamon installed.

### CODE REVIEW

**Comment by schemar** [comment]
Thank you!! 🚀
Will this have any implications when cinnamon *is* installed?

**Comment by jhbruhn** [comment]
I haven't tried, but as long as the cinnamon version is equivalent to the version specified in the PKGBUILD it should work fine. An alternative would be to detect whether cinnamon is installed during build, but that would lead to problems when you install cinnamon after you install this package. 

Am 1. August 2020 17:47:46 MESZ schrieb Martin Schenck <notifications@github.com>:

**Comment by Omnikron13** [comment]
Well, that'll teach me to run more test builds the next time the upstream inevitably moves. =P

To dig a little deeper on the options here, this would be the KISS version. The alternative non-KISS version would be to allow autodetection if cinnamon/gnome-shell are installed, falling back to reading the latest possible version from the upstream arc sources (the versions available are all directories under common/cinnamon).

Trying to be overly clever with this though risks more of a maintenance burden if/when there are further changes to the structure upstream, etc. so it's probably best to stick with the simple version and let end users change the version variable manually if for whatever reason they need to build for older versions.

**Comment by schemar** [comment]
Thanks!! 🤗 
Let's do it like this until someone else complains 😬

**Pull request merged**
