### PR TITLE
Contrast improvements

### PR DESCRIPTION
**Pull request by Omnikron13**

### CODE REVIEW

**Comment by Omnikron13** [comment]
Hope you don't mind, I've added patches for re-rendering xfwm4 assets as well.

**Comment by schemar** [comment]
I can't seem to make out any actual changes to the colors. Are you sure you created the PR correctly? Which colors were changed?

**Comment by schemar** [comment]
Thank you @Omnikron13 ! 🎉 
See #16 for a discussion on these changes.

**Comment by schemar** [comment]
I still need to apply these changes to the actual repo, which should probably be revisited 🤔  ...

**Pull request merged**
