### PR TITLE
Merging in automated patching over upstream source

### PR DESCRIPTION
**Pull request by Omnikron13**
This would merge in all the changes made in my fork, if you want to review them.

The tl;dr is:

- bases from the new upstream (https://github.com/NicoHood/arc-theme)
- solarize.sh pulls source and unzips to `./arc-theme-[version]/` 
- that tree is patched, leaving the user to run `autogen.sh` & `make` there however they wish

If you think this is an acceptable workflow for people building & packaging, can merge this in and wind up the fork.

### CODE REVIEW

**Comment by schemar** [comment]
Thanks! I think pulling the latest Arc and patching it definitely makes sense. However, I also think the latest version of the patched Arc should be part of this repository so that a user can simply clone and install. What do you think?

**Comment by Omnikron13** [comment]
Hm, well, we could include the latest patched source in the repo to make things quicker for users, though it's worth noting that the longest part of the build/install process is the `make` step in the patched source rather than the patching, as it has to export & optimise all the png assets (in the new upstream they have switched around when/how those assets get rendered).

We could run the make for them and check in all the pre-built png (& css, etc.) assets as well, but at that point maybe it'd be cleaner to just release a tarball of the completely built themes?

Maybe it's just me that feels a little iffy about checking in a source tree that has already had `autogen.sh` & `make` run in it though?

**Comment by schemar** [comment]
You are right. It usually makes no sense to commit generated code.
The problem I see is with things like, for example, the [AUR package]. Although it seems the [AUR package] is not really in use any more, so maybe we could just delete that. I am a little detached, as I switched from Linux to Mac more than a year ago and can't really use this theme myself any more 😢 

Any ways, the best thing is probably a clean repo. I suggest we do as you suggested and in addition comment on the [AUR package]. I didn't even realize there was a new upstream at https://github.com/NicoHood/arc-theme 😅

One additional suggestion, though: you download and patch files into an `arc-theme-...` directory. That could potentially conflict with an actually installed [Arc theme]. Is there an easy way to name the relevant files and folders `solarc-theme-...` instead? 🤔
Or is `sed -i "s/Arc/SolArc/g" configure.ac;` [here](https://github.com/schemar/solarc-theme/pull/27/files#diff-e24945fbcdf149dde54992748b9dc384R219) actually sufficient to prevent conflicts?

[arc theme]: https://github.com/NicoHood/arc-theme
[aur package]: https://aur.archlinux.org/packages/gtk-theme-solarc-git/

**Comment by Omnikron13** [comment]
Hm, yeah, I'll need to flag the AUR package as out of date. The PKGBUILD should be easy enough to update though, if the maintainer is still interested. Or failing that I could just see if I can take over the maintenance and update it I suppose. =P

So long as `solarize.sh` is kept in its own clean directory then there shouldn't be any conflict issues as its only the arc source directory that is called `arc-theme-*`; the built themes get called `SolArc`, `SolArc-Dark` & `SolArc-Darker`. I'm _pretty_ sure I've got it replacing the name everywhere it needs to, though I've not had an opportunity to test the Unity support yet.

So for now I'll merge this in as-is, and get to working on a source & pre-built tagged release and put things in motion over at the AUR. (Is there anywhere else its been packaged that I should chase up as well?)

**Comment by schemar** [comment]
Thanks! ❤️ 

I only remember the AUR. We should also draft a new (major) release. Do you want to do that?

**Pull request merged**
